import { useState } from 'react'
import { useApp } from '../context/AppContext'
import type { PinAssignment } from '../types/chip'
import { generateEsphomeConfig } from '../data/info/esphome'
import { ExportActions } from './ExportActions'

function generateArduinoDefines(chip: { name: string }, mapping: PinAssignment[]): string {
  if (mapping.length === 0) return '// No pins mapped yet'
  const lines = [
    `// Pin mapping for ${chip.name}`,
    `// Generated by ESP32 Pinout Studio`,
    '',
    ...mapping.map(a => `#define PIN_${a.label.toUpperCase().replace(/\s+/g, '_').replace(/[^A-Z0-9_]/g, '')} ${a.gpio}  // ${a.role}`),
  ]
  return lines.join('\n')
}

export function ExportPanel() {
  const { chip, mapping, shareUrl } = useApp()
  const [copied, setCopied] = useState<'url' | 'code' | 'esphome' | null>(null)

  const code = generateArduinoDefines(chip, mapping)
  const esphome = generateEsphomeConfig(chip, mapping)

  const copyText = async (text: string, type: 'url' | 'code' | 'esphome') => {
    await navigator.clipboard.writeText(text)
    setCopied(type)
    setTimeout(() => setCopied(null), 2000)
  }

  return (
    <div className="space-y-4">
      <h2 className="text-sm font-semibold text-gray-300">Export</h2>

      {/* Shareable URL */}
      <div>
        <label className="text-xs text-gray-500 block mb-1">Shareable URL</label>
        <div className="flex gap-2">
          <input
            readOnly
            value={shareUrl}
            className="flex-1 bg-gray-800 border border-gray-700 rounded px-2 py-1.5 text-xs text-gray-300 font-mono overflow-hidden"
          />
          <button
            onClick={() => copyText(shareUrl, 'url')}
            className="px-3 py-1.5 bg-gray-700 hover:bg-gray-600 rounded text-xs text-gray-200 whitespace-nowrap transition-colors"
          >
            {copied === 'url' ? '✓ Copied' : 'Copy'}
          </button>
        </div>
      </div>

      {/* Arduino #defines */}
      <div>
        <label className="text-xs text-gray-500 block mb-1">Arduino / PlatformIO</label>
        <pre className="bg-gray-800 border border-gray-700 rounded p-3 text-xs font-mono text-green-400 overflow-x-auto whitespace-pre max-h-48">
          {code}
        </pre>
        <button
          onClick={() => copyText(code, 'code')}
          className="mt-2 px-3 py-1.5 bg-gray-700 hover:bg-gray-600 rounded text-xs text-gray-200 transition-colors"
        >
          {copied === 'code' ? '✓ Copied' : 'Copy code'}
        </button>
      </div>

      {/* ESPHome config - boards only (ESPHome targets a dev board, not a bare module) */}
      <div>
        <label className="text-xs text-gray-500 block mb-1">ESPHome</label>
        {esphome ? (
          <>
            <pre className="bg-gray-800 border border-gray-700 rounded p-3 text-xs font-mono text-green-400 overflow-x-auto whitespace-pre max-h-64">
              {esphome}
            </pre>
            <button
              onClick={() => copyText(esphome, 'esphome')}
              className="mt-2 px-3 py-1.5 bg-gray-700 hover:bg-gray-600 rounded text-xs text-gray-200 transition-colors"
            >
              {copied === 'esphome' ? '✓ Copied' : 'Copy config'}
            </button>
          </>
        ) : (
          <p className="text-xs text-gray-600">
            Select a dev board (BOARDS tab) to generate an ESPHome config. ESPHome runs on boards, not bare modules.
          </p>
        )}
      </div>

      {/* PNG / PDF - also mirrored in the sticky header so they stay reachable */}
      <ExportActions variant="panel" />

    </div>
  )
}
